; ; PlatformIO Project Configuration File
; ;
; ;   Build options: build flags, source filter
; ;   Upload options: custom upload port, speed and extra flags
; ;   Library options: dependencies, extra library storages
; ;   Advanced options: extra scripting
; ;
; ; Please visit documentation for the other options and examples
; ; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1-n8r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc1-n8r8
framework = arduino
build_type = debug
board_build.filesystem = littlefs
lib_deps = 
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    bblanchon/ArduinoJson @ ^7.0.4
	FastLED
    Single_WS2812_Bitbang_Write
build_flags = 
	-O0 -g -ggdb
	-D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
upload_protocol = esptool
monitor_speed = 115200
monitor_filters = default, time, esp32_exception_decoder
debug_tool = esp-builtin
debug_speed = 20000
debug_init_break = tbreak setup
	
