M48
; DRILL file KiCad 10.0.0 date 2026-04-23T21:33:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-23T21:33:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X120.0Y-22.0
X120.0Y-101.0
X125.0Y-92.0
X147.0Y-21.0
X164.0Y-54.0
X175.0Y-101.0
M30
